name: union_shop
description: "A Flutter project for the University of Portsmouth union shop."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  test_cov_console: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/university_hoodie.png
    - assets/images/university_t-shirt.png
    - assets/images/university_lanyard.png
    - assets/images/university_joggers.png
    - assets/images/university_shirt-man.png
    - assets/images/university_t-shirt2.jpg
    - assets/images/university_stationary.jpg
    - assets/images/university_mug.jpg
    - assets/images/university_graduation.jpg
    - assets/images/university_summer.jpg
    - assets/images/hoodies_sweatshirts.jpg